// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRWZQlThpb4TXyIcnW-6AolfINVFm9CV8',
    appId: '1:875319477382:web:e42576a889ed8ca05efd07',
    messagingSenderId: '875319477382',
    projectId: 'mydear-diary',
    authDomain: 'mydear-diary.firebaseapp.com',
    storageBucket: 'mydear-diary.firebasestorage.app',
    measurementId: 'G-E2TB5LQ1MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1DRpZqZv9CoMUxkzYOt5nQ3VPCEcuLnc',
    appId: '1:875319477382:android:609425aa22c74e045efd07',
    messagingSenderId: '875319477382',
    projectId: 'mydear-diary',
    storageBucket: 'mydear-diary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_4ouk86SJ4pMD66Qs8Kxgeenzm6LQY5E',
    appId: '1:875319477382:ios:c788c87905908d975efd07',
    messagingSenderId: '875319477382',
    projectId: 'mydear-diary',
    storageBucket: 'mydear-diary.firebasestorage.app',
    iosBundleId: 'com.example.mydearDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_4ouk86SJ4pMD66Qs8Kxgeenzm6LQY5E',
    appId: '1:875319477382:ios:c788c87905908d975efd07',
    messagingSenderId: '875319477382',
    projectId: 'mydear-diary',
    storageBucket: 'mydear-diary.firebasestorage.app',
    iosBundleId: 'com.example.mydearDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRWZQlThpb4TXyIcnW-6AolfINVFm9CV8',
    appId: '1:875319477382:web:54b480fd8a0f61d65efd07',
    messagingSenderId: '875319477382',
    projectId: 'mydear-diary',
    authDomain: 'mydear-diary.firebaseapp.com',
    storageBucket: 'mydear-diary.firebasestorage.app',
    measurementId: 'G-4TF2760K5C',
  );
}
